use std::sync::Arc; use uuid::Uuid;
use crate::{dao::NewsletterDao,error::AppError,middleware::auth::AuthContext,models::{newsletter::{Newsletter,NewsletterListResponse,PublishNewsletterBody,UpsertNewsletterBody},notification::CreateNotification,schema::UserRole},services::NotificationService};
pub struct NewsletterService { dao: NewsletterDao, notifications: Arc<NotificationService> }
impl NewsletterService { pub fn new(dao: NewsletterDao, notifications: Arc<NotificationService>)->Self{Self{dao,notifications}}
 fn superadmin(auth:&AuthContext)->Result<(),AppError>{if matches!(auth.role,UserRole::SuperAdmin){Ok(())}else{Err(AppError::Authorization("Only Super Admins can manage newsletters".into()))}}
 fn validate(body:&UpsertNewsletterBody)->Result<(),AppError>{if body.title.trim().is_empty(){return Err(AppError::Validation("Newsletter title is required".into()))}if !["school","classrooms"].contains(&body.audience_scope.as_str()){return Err(AppError::Validation("Invalid audience scope".into()))}if body.audience_scope=="classrooms"&&body.classroom_ids.is_empty(){return Err(AppError::Validation("Select at least one classroom".into()))}if body.rendered_html.len()>500_000{return Err(AppError::Validation("Newsletter HTML is too large".into()))}Ok(())}
 pub async fn create(&self,auth:&AuthContext,body:UpsertNewsletterBody)->Result<Newsletter,AppError>{Self::superadmin(auth)?;Self::validate(&body)?;self.dao.create(&body,auth.user_id).await}
 pub async fn list(&self,auth:&AuthContext,school:Option<Uuid>,limit:i64,offset:i64)->Result<NewsletterListResponse,AppError>{let(limit,offset)=(limit.clamp(1,50),offset.max(0));let(total,items)=match auth.role {UserRole::Parent=>{let(i,t)=self.dao.list_parent(auth.user_id,limit,offset).await?;(t,i)},UserRole::SuperAdmin=>{let(i,t)=self.dao.list_admin(school,limit,offset).await?;(t,i)},_=>{let(i,t)=self.dao.list_admin(Some(auth.school_id),limit,offset).await?;(t,i)}};Ok(NewsletterListResponse{items,total})}
 pub async fn detail(&self,auth:&AuthContext,id:Uuid)->Result<Newsletter,AppError>{let list=self.list(auth,None,50,0).await?;list.items.into_iter().find(|n|n.id==id).ok_or_else(||AppError::NotFound("Newsletter not found".into()))}
 pub async fn publish(&self,auth:&AuthContext,id:Uuid,body:PublishNewsletterBody)->Result<Newsletter,AppError>{Self::superadmin(auth)?;let scheduled=body.scheduled_at.is_some();let n=self.dao.publish(id,body.scheduled_at,body.school_timezone.unwrap_or_else(||"UTC".into()),body.reminder_offsets_days).await?;if !scheduled { for user_id in self.dao.recipient_ids(id).await? { self.notifications.notify_user(user_id,CreateNotification{school_id:n.school_id,notification_type:"newsletter_published".into(),title:"New school newsletter".into(),body:n.title.clone(),related_entity_id:Some(id),related_entity_type:Some("newsletter".into()),action_url:Some("/news-pad".into())}).await; }} Ok(n)}
 pub async fn archive(&self,auth:&AuthContext,id:Uuid)->Result<(),AppError>{Self::superadmin(auth)?;self.dao.archive(id).await}
}
