use std::sync::Arc;
use axum::{extract::{Extension, Path, Query, State}, response::Json};
use uuid::Uuid;
use crate::{error::AppError, middleware::auth::{AuthContext, check_permission_admin_or_superadmin, check_permission_school_access}, models::{document_request::*, email::BulkEmailResponse, schema::UserRole}, services::DocumentRequestService};

fn admin(auth:&AuthContext)->bool { matches!(auth.role,UserRole::Admin|UserRole::SuperAdmin) }

pub async fn create_document_request(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Json(request):Json<CreateDocumentRequest>)->Result<Json<DocumentRequestSummary>,AppError>{check_permission_admin_or_superadmin(&auth,&request.school_id)?;Ok(Json(service.create(request,auth.user_id).await?))}
pub async fn publish_document_request(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Path(id):Path<Uuid>)->Result<Json<DocumentRequestSummary>,AppError>{let item=service.request_summary(id).await?;check_permission_admin_or_superadmin(&auth,&item.school_id)?;Ok(Json(service.publish(id,auth.user_id).await?))}
pub async fn list_document_requests(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Query(q):Query<DocumentRequestQuery>)->Result<Json<Vec<DocumentRequestSummary>>,AppError>{check_permission_admin_or_superadmin(&auth,&q.school_id)?;Ok(Json(service.list(&q).await?))}
#[derive(serde::Deserialize)] pub struct RecipientsQuery{pub school_id:Uuid,pub audience:String}
pub async fn document_recipients(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Query(q):Query<RecipientsQuery>)->Result<Json<Vec<DocumentRecipient>>,AppError>{check_permission_admin_or_superadmin(&auth,&q.school_id)?;if !matches!(q.audience.as_str(),"student"|"employee"){return Err(AppError::Validation("Invalid audience".into()));}Ok(Json(service.recipients(q.school_id,&q.audience).await?))}
pub async fn list_document_assignments(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Query(q):Query<DocumentAssignmentQuery>)->Result<Json<PagedDocumentAssignments>,AppError>{check_permission_admin_or_superadmin(&auth,&q.school_id)?;Ok(Json(service.assignments(&q,None,false).await?))}
pub async fn send_document_reminders(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Json(request):Json<DocumentReminderRequest>)->Result<Json<BulkEmailResponse>,AppError>{check_permission_admin_or_superadmin(&auth,&request.school_id)?;Ok(Json(service.send_reminders(request,auth.user_id).await?))}
pub async fn document_review_queue(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Query(q):Query<DocumentAssignmentQuery>)->Result<Json<PagedDocumentAssignments>,AppError>{check_permission_admin_or_superadmin(&auth,&q.school_id)?;Ok(Json(service.assignments(&q,None,true).await?))}
pub async fn my_document_assignments(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Query(q):Query<DocumentAssignmentQuery>)->Result<Json<PagedDocumentAssignments>,AppError>{check_permission_school_access(&auth,&q.school_id)?;Ok(Json(service.assignments(&q,Some(auth.user_id),false).await?))}
pub async fn document_upload_intent(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Path(id):Path<Uuid>,Json(body):Json<UploadIntentRequest>)->Result<Json<UploadIntentResponse>,AppError>{let school=service.assignment_school(id,auth.user_id,admin(&auth)).await?;check_permission_school_access(&auth,&school)?;Ok(Json(service.upload_intent(id,auth.user_id,admin(&auth),&body).await?))}
pub async fn complete_document_upload(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Path(id):Path<Uuid>,Json(body):Json<CompleteUploadRequest>)->Result<Json<DocumentAssignmentItem>,AppError>{let school=service.assignment_school(id,auth.user_id,admin(&auth)).await?;check_permission_school_access(&auth,&school)?;Ok(Json(service.complete_upload(id,auth.user_id,admin(&auth),&body).await?))}
pub async fn review_document_assignment(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Path(id):Path<Uuid>,Json(body):Json<ReviewDocumentAssignmentRequest>)->Result<Json<DocumentAssignmentItem>,AppError>{if !admin(&auth){return Err(AppError::Authorization("Admin access required".into()));}let school=service.assignment_school(id,auth.user_id,true).await?;check_permission_admin_or_superadmin(&auth,&school)?; Ok(Json(service.review(id,auth.user_id,&body).await?))}
#[derive(serde::Deserialize)] pub struct FileQuery{pub download:Option<bool>}
pub async fn document_file_url(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Path(id):Path<Uuid>,Query(q):Query<FileQuery>)->Result<Json<FileAccessResponse>,AppError>{let assignment=service.submission_assignment(id).await?;let school=service.assignment_school(assignment,auth.user_id,admin(&auth)).await?;check_permission_school_access(&auth,&school)?;Ok(Json(service.file_url(id,auth.user_id,admin(&auth),q.download.unwrap_or(false)).await?))}
pub async fn document_assignment_history(State(service):State<Arc<DocumentRequestService>>,Extension(auth):Extension<AuthContext>,Path(id):Path<Uuid>)->Result<Json<Vec<DocumentAuditEvent>>,AppError>{let school=service.assignment_school(id,auth.user_id,admin(&auth)).await?;check_permission_school_access(&auth,&school)?;Ok(Json(service.history(id,auth.user_id,admin(&auth)).await?))}
