# fly.toml app configuration file generated for goddard on 2025-10-18T08:39:43+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goddard'
primary_region = 'dfw'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
