use chrono::{DateTime, Utc}; use deadpool_postgres::Pool; use serde_json::{json, Value}; use uuid::Uuid;
use crate::{error::AppError, models::newsletter::{Newsletter, UpsertNewsletterBody}};
#[derive(Clone)] pub struct NewsletterDao { pool: Pool }
impl NewsletterDao { pub fn new(pool: Pool) -> Self { Self { pool } }
 fn row(row: &tokio_postgres::Row) -> Newsletter { Newsletter { id: row.get("id"), school_id: row.get("school_id"), title: row.get("title"), content_blocks: row.get("content_blocks"), rendered_html: row.get("rendered_html"), audience_scope: row.get("audience_scope"), classroom_ids: row.get("classroom_ids"), status: row.get("status"), scheduled_at: row.get("scheduled_at"), school_timezone: row.get("school_timezone"), reminder_offsets_days: row.get("reminder_offsets_days"), published_at: row.get("published_at"), archived_at: row.get("archived_at"), created_at: row.get("created_at"), updated_at: row.get("updated_at"), applicable_children: row.try_get("applicable_children").ok() } }
 async fn classrooms(client: &tokio_postgres::Client, id: Uuid) -> Result<Vec<Uuid>, AppError> { Ok(client.query("SELECT classroom_id FROM newsletter_audiences WHERE newsletter_id=$1 ORDER BY classroom_id", &[&id]).await.map_err(|e| AppError::Database(e.to_string()))?.into_iter().map(|r| r.get(0)).collect()) }
 pub async fn create(&self, body: &UpsertNewsletterBody, user_id: Uuid) -> Result<Newsletter, AppError> { let mut c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?; let tx=c.transaction().await.map_err(|e|AppError::Database(e.to_string()))?; tx.execute("SELECT set_config('app.current_user_id',$1,true)",&[&user_id.to_string()]).await.ok(); let r=tx.query_one("INSERT INTO newsletters (school_id,title,content_blocks,rendered_html,audience_scope,school_timezone,reminder_offsets_days,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING id,school_id,title,content_blocks,rendered_html,audience_scope,status,scheduled_at,school_timezone,reminder_offsets_days,published_at,archived_at,created_at,updated_at", &[&body.school_id,&body.title,&body.content_blocks,&body.rendered_html,&body.audience_scope,&body.school_timezone.clone().unwrap_or_else(||"UTC".into()),&body.reminder_offsets_days,&user_id]).await.map_err(|e|AppError::Database(e.to_string()))?; let id:Uuid=r.get("id"); for class_id in &body.classroom_ids { tx.execute("INSERT INTO newsletter_audiences(newsletter_id,classroom_id) VALUES($1,$2)",&[&id,class_id]).await.map_err(|e|AppError::Database(e.to_string()))?; } tx.commit().await.map_err(|e|AppError::Database(e.to_string()))?; self.get_admin(id).await?.ok_or_else(||AppError::NotFound("Newsletter not found".into())) }
 pub async fn get_admin(&self,id:Uuid)->Result<Option<Newsletter>,AppError>{let c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?; let r=c.query_opt("SELECT n.*, COALESCE(array_agg(na.classroom_id) FILTER (WHERE na.classroom_id IS NOT NULL),'{}') classroom_ids FROM newsletters n LEFT JOIN newsletter_audiences na ON na.newsletter_id=n.id WHERE n.id=$1 GROUP BY n.id",&[&id]).await.map_err(|e|AppError::Database(e.to_string()))?;Ok(r.map(|r|Self::row(&r)))}
 pub async fn list_admin(&self, school_id: Option<Uuid>, limit:i64,offset:i64)->Result<(Vec<Newsletter>,i64),AppError>{let c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?;let rows=c.query("SELECT n.*,COALESCE(array_agg(na.classroom_id) FILTER (WHERE na.classroom_id IS NOT NULL),'{}') classroom_ids,COUNT(*) OVER() total FROM newsletters n LEFT JOIN newsletter_audiences na ON na.newsletter_id=n.id WHERE n.is_active AND ($1::uuid IS NULL OR n.school_id=$1) GROUP BY n.id ORDER BY COALESCE(n.published_at,n.scheduled_at,n.created_at) DESC LIMIT $2 OFFSET $3",&[&school_id,&limit,&offset]).await.map_err(|e|AppError::Database(e.to_string()))?;let total=rows.first().map(|r|r.get("total")).unwrap_or(0);Ok((rows.iter().map(Self::row).collect(),total))}
 pub async fn list_parent(&self,user:Uuid,limit:i64,offset:i64)->Result<(Vec<Newsletter>,i64),AppError>{let c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?;let rows=c.query("SELECT n.*, '{}'::uuid[] classroom_ids, r.applicable_children, COUNT(*) OVER() total FROM newsletter_recipients r JOIN newsletters n ON n.id=r.newsletter_id WHERE r.user_id=$1 AND n.status='published' AND n.is_active ORDER BY n.published_at DESC LIMIT $2 OFFSET $3",&[&user,&limit,&offset]).await.map_err(|e|AppError::Database(e.to_string()))?;let total=rows.first().map(|r|r.get("total")).unwrap_or(0);Ok((rows.iter().map(Self::row).collect(),total))}
 pub async fn publish(&self,id:Uuid,at:Option<DateTime<Utc>>,timezone:String,reminders:Vec<i16>)->Result<Newsletter,AppError>{let c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?;let scheduled=at.is_some();let row=c.query_one("UPDATE newsletters SET status=CASE WHEN $2 THEN 'scheduled' ELSE 'published' END, scheduled_at=$1, school_timezone=$3, reminder_offsets_days=$4, published_at=CASE WHEN $2 THEN NULL ELSE NOW() END, updated_at=NOW() WHERE id=$5 AND is_active RETURNING id",&[&at,&scheduled,&timezone,&reminders,&id]).await.map_err(|e|AppError::Database(e.to_string()))?;let _ :Uuid=row.get(0);if !scheduled { self.snapshot_recipients(id).await?; } self.get_admin(id).await?.ok_or_else(||AppError::NotFound("Newsletter not found".into()))}
 pub async fn snapshot_recipients(&self,id:Uuid)->Result<(),AppError>{let c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?;c.execute("INSERT INTO newsletter_recipients(newsletter_id,user_id,school_id,applicable_children) SELECT n.id,u.id,n.school_id,jsonb_agg(jsonb_build_object('childId',ch.id,'classroomId',e.classroom_id,'classroomName',cl.name)) FROM newsletters n JOIN children ch ON ch.school_id=n.school_id JOIN enrollments e ON e.child_id=ch.id JOIN classrooms cl ON cl.id=e.classroom_id JOIN users u ON u.id=ch.parent_id OR u.id=ch.secondary_parent_id WHERE n.id=$1 AND n.status='published' AND COALESCE(u.is_active,true) AND (n.audience_scope='school' OR EXISTS(SELECT 1 FROM newsletter_audiences a WHERE a.newsletter_id=n.id AND a.classroom_id=e.classroom_id)) GROUP BY n.id,u.id,n.school_id ON CONFLICT(newsletter_id,user_id) DO NOTHING",&[&id]).await.map_err(|e|AppError::Database(e.to_string()))?;Ok(())}
 pub async fn archive(&self,id:Uuid)->Result<(),AppError>{let c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?;c.execute("UPDATE newsletters SET status='archived',archived_at=NOW(),updated_at=NOW() WHERE id=$1",&[&id]).await.map_err(|e|AppError::Database(e.to_string()))?;Ok(())}
 pub async fn recipient_ids(&self,id:Uuid)->Result<Vec<Uuid>,AppError>{let c=self.pool.get().await.map_err(|e|AppError::Database(e.to_string()))?;Ok(c.query("SELECT user_id FROM newsletter_recipients WHERE newsletter_id=$1",&[&id]).await.map_err(|e|AppError::Database(e.to_string()))?.into_iter().map(|r|r.get(0)).collect())}
}
